version: "3"
services:
  web:
    image: nginx:latest
    ports:
      - "8000:80"
    depends_on:
      - app
    volumes:
      - ./web/default.conf:/etc/nginx/conf.d/default.conf
      - ./app:/var/www/
  app:
    image: php:7.2.15-fpm
    volumes:
      - ./app:/var/www/
